name: Broken-Links

on:
  push:
    branches: main
  pull_request:
    branches: main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run once a week
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Restore Lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run Lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: "--config .lychee.toml --cache --max-cache-age 1d ."
        continue-on-error: true

      - name: Create Issue From File
        if: steps.lychee.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
