name: Valid Links

on:
  push:
    branches: main
  pull_request:
    branches: main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run once a week
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    name: Check Link Validity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: "--no-progress --config .lychee.toml ."
        continue-on-error: true

      - name: Create Issue From File
        if: steps.lychee.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
